# Generated by Django 3.2.12 on 2022-05-19 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
        ('clouds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Drop',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='drop',
        ),
    ]
