# Generated by Django 3.2.12 on 2022-05-25 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clouds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='like_users',
            field=models.ManyToManyField(null=True, related_name='like_drops', to=settings.AUTH_USER_MODEL),
        ),
    ]
